# Generated by Django 5.0.7 on 2024-09-21 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBook',
            fields=[
                ('artbook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.artbook')),
            ],
            bases=('books.artbook',),
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='ArtBook',
        ),
    ]
