# Generated by Django 5.0.7 on 2024-09-08 04:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_id_alter_book_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uuid',
        ),
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f9ed076-4cb8-4e72-91e4-6a24f13136b4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
