# Generated by Django 5.0.7 on 2024-09-08 04:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_uuid_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('956cf76e-a471-43a3-90c0-f1a2f00d4e62'), editable=False, primary_key=True, serialize=False),
        ),
    ]
